mybatis:
  #mapper config
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
#  http://localhost:8080/h2-console
  servlet:
    multipart:
      max-file-size: 50MB      
      max-request-size: 100MB  
logging:
  level:
    com.example: debug
    org.mybatis: debug

property:
  jwt:
    admin-secret-key: music
    admin-ttl: 7200000
    admin-token-name: token

app:
  security:
    jwt:
      enabled: true
